# Generated by Django 5.1 on 2024-09-18 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='\x08log\\default.jpg', upload_to='blog/'),
        ),
    ]
